# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
        -   id: fmt
        -   id: clippy
        -   id: cargo-check
