[package]
name = "jp2gmd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.20.1"
eframe = "0.20.1"
num-rational = "0.4.1"
num-traits = "0.2.15"
anyhow = "1.0.66"
lazy_static = "1.4.0"
serde = { version = "1.0.151", features = ["derive"] }
