[package]
name = "jp2gmd"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "jp2gmd"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.19.0"
num-rational = "0.4.1"
num-traits = "0.2.15"
anyhow = "1.0.66"
