load("@rules_rust//rust:defs.bzl", "rust_library")

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "fractal_clock",
    srcs = ["src/fractal_clock.rs"],
    deps = [
        "@crate_index//:egui",
    ],
)
